name: Deploy BMS Server

# 当推送到 main 分支时触发
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # 1. 检出最新代码
      - name: Checkout Code
        uses: actions/checkout@v3

      # 2. 将代码自动传送到腾讯云服务器的对应目录
      - name: Copy files via SCP
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 22
          source: "."
          target: "/opt/1panel/whwkkj-web/bms-project/bms-server"
          overwrite: true

      # 3. 登录服务器并重启 Python 容器使代码生效
      - name: Restart Python Container
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 22
          script: |
            # 重启你的 Python 容器 
            docker restart bms-server