name: Deploy BMS Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v5

      - name: Upload BMS Server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 22

          source: "*"
          target: "/opt/1panel/whwkkj-web/bms-project/bms-server"
          overwrite: true


      - name: Check requirements changes
        id: changes
        run: |
          if git diff --name-only HEAD^ HEAD | grep -q "DX-CT511N/requirements.txt"; then
            echo "requirements_changed=true" >> "$GITHUB_OUTPUT"
          else
            echo "requirements_changed=false" >> "$GITHUB_OUTPUT"
          fi


      - name: Install Dependencies
        if: steps.changes.outputs.requirements_changed == 'true'
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            sudo docker exec bms-server pip install -r requirements.txt


      - name: Restart BMS Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 22
          script: |
            sudo docker ps --filter "name=bms-server"